### ISSUE TITLE
Make the website more prominent in "roboclub" google search

### ISSUE THREAD

**Issue by ayeohmy** [CMU-Robotics-Club/roboticsclub.org#77]
Make our website come up as the first hit when someone searches "roboclub" on google. Cause we haz to have it. 

- love, A

**Comment by bstrysko** [comment]
Added "roboclub" to About page.

**Comment by bstrysko** [comment]
Closing since Facebook thread seems satisfied with current ranking.

**Comment by Corrain** [comment]
When you google search "roboclub github" this is the first page that pops up :P
